sudo: required
services:
    - docker

before_install:
    - docker build -t harvinderg/docker-react -f Dockerfile.dev . 

script:
    - docker run harvinderg/docker-react npm run test -- --coverage
    